### ISSUE TITLE
Allow custom components

### ISSUE THREAD

**Issue by MarcinusX** [Fidev-io/framy#8]
- [x] Simple widgets without any dependencies #39
- [x] Changing primitive dependencies in UI (String, int, boolean) #40
- [x] Changing custom class dependencies (e.g. User object as a parameter) #41
- [x] Defining presets (default configurations of dependencies) #42
- [x] Support for List dependencies #47
- [x] Set widget dependency to null #48
